# Generated by Django 6.0.1 on 2026-02-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactmessage_department_doctor_delete_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
    ]
